### PR TITLE
create default stylesheet #27

### PR DESCRIPTION
**Pull request by piensaenpixel**
Related - https://github.com/CartoDB/CartoAssets/issues/27

cc @xavijam

### CODE REVIEW

**Comment by xavijam** [comment]
Why don't we add "vendor" reset stylesheet inside "cdb-utilities"? cc @javierarce 
Also, could we rename default stylesheet to... uhm... custom-reset.scss?

**Comment by xavijam** [comment]
And, we should check how those changes could affect deep-insights and cartodb.js modules.

**Comment by javierarce** [comment]
I like the `vendor` folder idea, but I'm not sure if it'll contain other thing that the reset.css file. 
Instead of `default.css.scss` I'd say `defaults.css.scss` with an `s`.

**Comment by piensaenpixel** [comment]
image

take a look!

**Comment by javierarce** [comment]
:+1: I'd also bump the package's version.

**Comment by piensaenpixel** [comment]
done

**Comment by javierarce** [comment]
:+1:

**Pull request merged**
