### PR TITLE
change loader

### PR DESCRIPTION
**Pull request by piensaenpixel**
@xavijam take a look

### CODE REVIEW

**Comment by xavijam** [comment]
Could you add a GIF and explain the changes 😬 ?

**Comment by piensaenpixel** [comment]
- Change the animation
- Change the design to improve the visibility
- Remove the animation when `is-visible`  is not applied

loader


about @eduardosada 's post, we are fixing some issues and we'll start with this one :), thanks a lot

**Comment by xavijam** [comment]
Ping!

**Review by xavijam — APPROVED** [review]
:es:

**Pull request merged**
