### PR TITLE
Chaning way to load CartoAssets stylesheets

### PR DESCRIPTION
**Pull request by xavijam**
Following the same process we started with CARTO.js and Deep-Insights, we have created the entry point for easy loading/generating the styles in CartoAssets. That solves the problem we have in BUILDER where CartoAssets classes are repeated and appeared several times.
Bad thing is we need to change the Sass task in CARTO.js (v4), DI and Builder, but I feel it is necessary.

- DI: https://github.com/CartoDB/deep-insights.js/pull/545.
- CARTO.js: https://github.com/CartoDB/cartodb.js/pull/1654.

cc @CartoDB/frontend @piensaenpixel

### CODE REVIEW

**Comment by xavijam** [comment]
I've found something testing it in Builder, so please, don't merge it.

**Comment by piensaenpixel** [comment]
Oh \o/

**Comment by xavijam** [comment]
I know you @matallo really appreciate this kind of changes so, what do you think?

**Comment by matallo** [comment]
:_____)

**Comment by xavijam** [comment]
Yep @nobuti, and it was not working :S.

**Comment by xavijam** [comment]
Adding them from node-modules was not super beautiful. What about copy and add them to a vendor folder each time grunt starts? @nobuti

**Comment by nobuti** [comment]
👍

**Comment by xavijam** [comment]
If all agree (mainly @matallo @piensaenpixel @nobuti), I'll merge wherever it needs tomorrow 💃 .

**Comment by nobuti** [comment]
Yesss

**Comment by matallo** [comment]
just a comment, to ignite discussion, otherwise I see CR 👍 

I don't feel quite comfortable adding source vendor files rather than the dist, as we need to compile (adding some extra ms to our build time)

in the ps README they provide a repo with such files
https://github.com/noraesae/perfect-scrollbar-bower

the repo seems to be sync with the actual releases, and even if we don't add them via bower, it can be added via npm and url, what do you think?

**Comment by matallo** [comment]
on a second thought this only applies to css, if we are to use Ps with require (i.e. `var Ps = require('perfect-scrollbar');`) we need to include it via npm so forget my last comment

**Review by matallo — APPROVED** [review]

**Comment by xavijam** [comment]
Merging!

**Pull request merged**
