### PR TITLE
fix class names

### PR DESCRIPTION
**Pull request by piensaenpixel**
@xavijam could you take a look? after merge this one i'll fix the markup in the editor.

### CODE REVIEW

**Comment by xavijam** [comment]
:+1:, bad thing is we should update new editor component using old classes.

**Comment by xavijam** [comment]
Could we fix the same problem in this file? -> https://github.com/CartoDB/CartoAssets/blob/master/src/scss/cdb-components/lists.scss

**Comment by piensaenpixel** [comment]
Done @xavijam

**Comment by xavijam** [comment]
:+1:

**Pull request merged**
