### PR TITLE
Menu fixes

### PR DESCRIPTION
**Pull request by javierarce**
A couple of minor modifications (see #70) to adapt the menu to the current use in the Editor.

CR: @piensaenpixel

### CODE REVIEW

**Comment by javierarce** [comment]
I think there's a problem with the underline, @piensaenpixel 

screenshot_16_02_16_16_57

**Comment by javierarce** [comment]
ping

**Comment by piensaenpixel** [comment]
Changes are perfect :) i'll fix now the underline

**Comment by piensaenpixel** [comment]
@javierarce take a look 

image

**Pull request merged**
